---
- name: Create alertmanager user
  user:
    name: alertmanager
    shell: /bin/false

- name: Create directories
  file:
    path: "{{ item }}"
    state: directory
    owner: alertmanager
    group: alertmanager
  loop:
    - /etc/alertmanager
    - /var/lib/alertmanager

- name: Download alertmanager
  get_url:
    url: https://github.com/prometheus/alertmanager/releases/download/v0.30.1/alertmanager-0.30.1.linux-amd64.tar.gz
    dest: /tmp/alertmanager.tar.gz
  delegate_to: localhost
  connection: local

- name: Extract alertmanager
  unarchive:
    src: /tmp/alertmanager.tar.gz
    dest: /tmp/
    remote_src: no

- name: Move binary to /usr/local/bin
  copy:
    src: /tmp/alertmanager-0.30.1.linux-amd64/alertmanager
    dest: /usr/local/bin/alertmanager
    remote_src: yes
    mode: '0755'
  loop:
    - alertmanager
    - amtool
  notify: restart alertmanager

- name: Create Config
  template:
    src: alertmanager.yml.j2
    dest: /etc/alertmanager/alertmanager.yml
    owner: alertmanager
    group: alertmanager
  notify: restart alertmanager

- name: Create Systemd Service file
  template:
    src: alertmanager.service.j2
    dest: /etc/systemd/system/alertmanager.service
  notify: Restart Node Exporter

- name: Start and Enable Node Exporter
  systemd:
    name: alertmanager
    state: started
    enabled: yes
    daemon_reload: yes